In [1]:
import numpy as np
import pandas as pd
import hashlib

In [2]:
np.random.seed(6)

users_num = 10000
mean_user_ctr = 0.2
beta = 20
alpha = mean_user_ctr * beta / (1 - mean_user_ctr)

df = pd.DataFrame()
df['user'] = range(users_num)
df['group'] = np.random.rand(users_num) < 0.5

df['base_user_ctr'] = np.random.beta(alpha, beta, size=users_num)
df['views'] = np.random.lognormal(mean=1, sigma=1, size=users_num).astype(int) + 1
df['clicks'] = np.random.binomial(df['views'], df['base_user_ctr'])

In [3]:
df.head(20)

    user  group  base_user_ctr  views  clicks
0      0  False       0.322688      2       2
1      1   True       0.182517      6       1
2      2  False       0.260975      6       3
3      3   True       0.260439      2       0
4      4   True       0.332355      1       1
5      5  False       0.361663      2       1
6      6  False       0.112639      3       0
7      7   True       0.296629     15       6
8      8   True       0.343276      3       1
9      9  False       0.068264      3       0
10    10   True       0.134971      8       0
11    11  False       0.213061      1       0
12    12  False       0.206636      1       0
13    13  False       0.204137      4       2
14    14  False       0.143004      2       0
15    15  False       0.326358     11       5
16    16  False       0.190332      4       0
17    17   True       0.115171      1       0
18    18  False       0.212781      2       0
19    19  False       0.200358      5       0

In [4]:
df["bucket"] = df['user'].apply(lambda x: int(hashlib.md5((str(x) + "my_salt").encode()).hexdigest(), 16) % 100)

In [46]:
new_df = df.groupby(['bucket']).agg({'views': 'sum', "clicks" : "sum", 'base_user_ctr': 'mean'}).reset_index()
new_df['group_ctr'] = new_df.clicks / new_df.views

In [44]:
std_base = new_df.loc[new_df['group'] == True, 'base_user_ctr'].std()
std_group = new_df.loc[new_df['group'] == True, 'group_ctr'].std()

In [49]:
std_base, std_group

(0.01099002858679458, 0.027713946269448585)